// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJyafDQPtGJOlpBQY4kfAty43o91XPmJc',
    appId: '1:57070185506:web:dcfa8c8eb70162abe56e7b',
    messagingSenderId: '57070185506',
    projectId: 'moptaste-79728',
    authDomain: 'moptaste-79728.firebaseapp.com',
    storageBucket: 'moptaste-79728.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL5bDP63fSYMz2lqq5mT63luKnMQaq5Fo',
    appId: '1:57070185506:android:f4b550e0c5cf6fa8e56e7b',
    messagingSenderId: '57070185506',
    projectId: 'moptaste-79728',
    storageBucket: 'moptaste-79728.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB77c88L893rRFlSzl8-Un595-oG7YYlDI',
    appId: '1:57070185506:ios:d5bff6692b40aa5de56e7b',
    messagingSenderId: '57070185506',
    projectId: 'moptaste-79728',
    storageBucket: 'moptaste-79728.firebasestorage.app',
    iosBundleId: 'com.example.moptaste',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB77c88L893rRFlSzl8-Un595-oG7YYlDI',
    appId: '1:57070185506:ios:d5bff6692b40aa5de56e7b',
    messagingSenderId: '57070185506',
    projectId: 'moptaste-79728',
    storageBucket: 'moptaste-79728.firebasestorage.app',
    iosBundleId: 'com.example.moptaste',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJyafDQPtGJOlpBQY4kfAty43o91XPmJc',
    appId: '1:57070185506:web:a25f51957897343ae56e7b',
    messagingSenderId: '57070185506',
    projectId: 'moptaste-79728',
    authDomain: 'moptaste-79728.firebaseapp.com',
    storageBucket: 'moptaste-79728.firebasestorage.app',
  );
}
